### ISSUE TITLE
Sub accounts list

### ISSUE THREAD

**Issue by jakemer** [justifi-tech/web-component-library#204]

**Comment by colganmeanor** [comment]
This component is mostly done, but final work cannot be completed until we can load data and test with actual data.  

Unable to access local capital while developing in storybook / web-components. Hitting CORS error when attempting to set capital's localhost port as API origin for web-components. 

Need to clarify how we're grabbing data for these platform components, either via capital or the proxy API before continuing to work on this task.

**Comment by colganmeanor** [comment]
This work is completed - but will hold off on releasing until we finalize our `.env` file and can release with the new env variables being used for this component
