### ISSUE TITLE
Export global scope component types

### ISSUE THREAD

**Issue by jakemer** [justifi-tech/web-component-library#243]
Right now our distributed code includes JSX typings for our web components, but it doesn't include them export them within the global scope. The goal is to be able to import the types into React applications, so that they don't have to manually be written so that TS linting passes.

It seems that this package/output target provided by Stencil should do exactly what we want if `customElementsExportBehavior` is set to `auto-define-custom-elements`
https://stenciljs.com/docs/custom-elements

**Comment by jakemer** [comment]
Right now our distributed code includes JSX typings for our web components, but it doesn't include them export them within the global scope. The goal is to be able to import the types into React applications, so that they don't have to manually be written so that TS linting passes.

It seems that this package/output target provided by Stencil should do exactly what we want if `customElementsExportBehavior` is set to `auto-define-custom-elements`
https://stenciljs.com/docs/custom-elements

**Comment by TiagoFuelber** [comment]
Helpful link: https://github.com/ionic-team/stencil/issues/1636
