### ISSUE TITLE
Web components 'apiOrigin' and 'iframeOrigin' props

### ISSUE THREAD

**Issue by jakemer** [justifi-tech/web-component-library#273]
Components take optional props for `apiOrigin` and `iframeOrigin` which will override the production values (currently in `config.ts`).

Storybook should be updated so that *in development* an environment picker is available and overrides `apiOrigin` and `iframeOrigin`. Document this as optional and used for internal testing

**Comment by TiagoFuelber** [comment]
Now with `.env` files this may be not necessary anymore
