### ISSUE TITLE
Define exportParts for gross-payment-chart component

### ISSUE THREAD

**Issue by colganmeanor** [justifi-tech/web-component-library#291]
Let's identify which CSS parts would be ideal to add as `@exportParts` to the `GrossPaymentChart` component. 

It likely doesn't need very many, but some ideas would be: 

 - Bar color
 - background color?
 - Tooltip color
 - Tooltip font color ?

**Comment by jakemer** [comment]
This will be tackled in our component CSS refactor, otherwise when it comes up as a customer ask
