### ISSUE TITLE
Pagination not disabled when there are no more results to show

### ISSUE THREAD

**Issue by jakemer** [justifi-tech/web-component-library#298]
Steps to reproduce:
- Go to https://storybook.justifi.ai/?path=/story/components-payoutslist--basic, see that there are only two results (we page by 25 I believe)
- Click "Next"
- The list will attempt to load more data and will render the generic "No results" message

We should either disable the next button or not show it (worth a search to see what is best practice)

**Comment by colganmeanor** [comment]
Investigating this issue this morning (01/29/2024) - unable to reproduce. 

Seems that the most recent change in this file might have inadvertently fixed this - the `onClick` event handler was moved from the `li` element to the `a` element - which IMO should be the one handling the event instead of the list element. 

```
<li
  onClick={(e) => {
    e.preventDefault();
    this.paging.handleClickPrevious(this.paging.start_cursor);
  }}
  part={`previous-button${this.paging.has_previous ? '' : ' button-disabled'}`}
  class={`page-item ${this.paging.has_previous ? '' : ' disabled'}`}
>
  <a href="#" class="page-link">
    <span class="me-1" part="arrow arrow-left">&laquo;</span>
    <span part="previous-button-text">Previous</span>
  </a>
</li>
```

========> 

```
<li class={`page-item ${this.paging.has_previous ? '' : ' disabled'}`}>
    <a href="#"
      class="page-link"
      onClick={(e) => {
        e.preventDefault();
        this.paging.handleClickPrevious(this.paging.start_cursor);
      }}
      part={`page-button${this.paging.has_previous ? '' : ' page-button-disabled'}`}>
      <span class="me-1" part="page-arrow">&laquo;</span>
      <span part="page-button-text">Previous</span>
    </a>
  </li>
```
