### ISSUE TITLE
BusinessDetails component appears broken with freshly created businesses with only legal name

### ISSUE THREAD

**Issue by jakemer** [justifi-tech/web-component-library#315]
The rendering of the BusinessDetails web component is incorrect when the business has only a legal name. From the provided image, there might be a missing null check somewhere in the code.

![Image](https://github.com/justifi-tech/web-component-library/assets/3867103/a1f089c9-a7e3-4cbc-8dd5-ccc0d37f7202)

**Comment by TiagoFuelber** [comment]
@jakemer is this a valid use case? Bearing in mind that in BusinessForm we can only create a business if all mandatory fields are filled in

**Comment by jakemer** [comment]
We should show the data we have, which is sometimes just the `legal_name`, and hide sections that are empty
