### ISSUE TITLE
BusinessFormStepped not currently displaying retreived business data

### ISSUE THREAD

**Issue by jakemer** [justifi-tech/web-component-library#316]
![Image](https://github.com/justifi-tech/web-component-library/assets/3867103/310bfefa-3056-4f1e-95b5-c9ce3297a9c5)

Additionally, it returns an `account_not_found` error when proceeding to the next step. I have set the props as defined in https://storybook.justifi.ai/?path=/story/components-businessformstepped--basic. If I missed any configuration, please let me know.

![Image](https://github.com/justifi-tech/web-component-library/assets/3867103/26e81793-57b1-4e55-b2bf-13bde983899f)

**Comment by colganmeanor** [comment]
Marking this as completed - as of #360
