### ISSUE TITLE
The status label styling for `PaymentsList` is missing background color

### ISSUE THREAD

**Issue by colganmeanor** [justifi-tech/web-component-library#319]
The PaymentList web component renders the payment status labels without colors; I expected something like the basic docs (https://storybook.justifi.ai/?path=/story/components-paymentslist--basic). Whether this is intentional is unclear, so maybe it’s not a bug.

![Image](https://github.com/justifi-tech/web-component-library/assets/3867103/c54c6bb7-0889-4281-8ae9-e3f1e6c78b72)

**Comment by colganmeanor** [comment]
Update 01/29/2024 - 

Looked into this today and it seems that the reason the styles aren't included in the screenshot example above is because the source file where the `payments-list` web component is rendered does not include a `link` tag in its header importing Bootstraps stylings. 

After looking at our `usage example` in the docs - I see it's not included there, so I believe we simply need to make sure to include that in example in our documentation so users don't forget to include it.

**Comment by jakemer** [comment]
I think the issue here is simply that the css is not being included from the CDN. Taking a look at the attached file, you will see that everything looks correct. If you remove the stylesheet, it looks like the screenshot on this issue.


[index.html.zip](https://github.com/justifi-tech/web-component-library/files/14451312/index.html.zip)

**Comment by TiagoFuelber** [comment]
I verified that linking the correct CSS file in `index.html` applied the intended styles successfully.

<img width="935" alt="image" src="https://github.com/justifi-tech/web-component-library/assets/22480988/e560150d-b9b2-4ab9-89cb-ea82c17aa926">
