### ISSUE TITLE
Write additional tests for business-form components

### ISSUE THREAD

**Issue by colganmeanor** [justifi-tech/web-component-library#323]
Currently our test coverage for the `business-form` components is minimal 

We have some basic test coverage to test that the `Prop` `auth-token` is correctly provided, but lack tests about the usage of the form itself. 

We have some recent issues that have been reported related to these components, so we should prioritize test coverage that addresses these types of issues that have surfaced. 

Test ideas:
- Mock API call to retrieve existing business details on the form. 
  - Should help catch issues such as [BusinessFormStepped not currently displaying retreived business data #316](https://github.com/justifi-tech/web-component-library/issues/316)
   - If data exists and is retrieved on API call - the form inputs should update to reflect the data
   - if data does not exist - form inputs should remain untouched

- [BusinessDetails component appears broken with freshly created businesses with only legal name #315](https://github.com/justifi-tech/web-component-library/issues/315)
   - form should still render if data is only partially present
   - IE - if only the a certain piece of the data is returned, we should still render the form with any values that are returned and can be placed on the form. 

- Should individual pieces of the business-form have their own unit test coverage? (`business-representative`, `business-owners`, etc)
  - IE something like testing that a given section populates correctly if data is present. 
  - Maybe we don't need test coverage on each of these, but something like `business-owners` could have some test coverage to ensure that the `Add Owner` functionality is working correctly and adds new elements to the DOM.

**Comment by jakemer** [comment]
Closing because this has overlap with #349
