### ISSUE TITLE
Mock api calls in tests for components that make api requests

### ISSUE THREAD

**Issue by colganmeanor** [justifi-tech/web-component-library#326]
The majority of our web components make a request to our backend API at some point - most of them attempt to grab data at render time. 

We should aim to write unit tests that mock these interactions with the API and ensure that mock data is correctly loaded, as well as errors are handled correctly in the event that data is not correctly received. 

The following components could benefit from this type of test coverage:

- `payments-list`
- `payment-details`
- `payouts-list`,
- `payout-details`
- `gross-payment-chart`
- `business-details`
- `business-form`
- `business-form-stepped`

**Comment by jakemer** [comment]
This was broken down into multiple smaller issues and can closed
