### ISSUE TITLE
Remove `account-id` as Business Form Prop

### ISSUE THREAD

**Issue by nhalm** [justifi-tech/web-component-library#337]
**Is your feature request related to a problem? Please describe.**
We currently have a prop on the business forms for `account_id`.  That prop doesn't make sense in context of business, or outside of the payments api.

**Describe the solution you'd like**
Remove the prop `account-id` in the business components.

**Describe alternatives you've considered**

**Additional context**

**Comment by jakemer** [comment]
Duplicate of #341
