### ISSUE TITLE
Enhance documentation for PaymentForm component

### ISSUE THREAD

**Issue by Claudia108** [justifi-tech/web-component-library#362]
**Is your feature request related to a problem? Please describe.**
Add more context to the documentation of the `PaymentForm` component that explains how to use it:
- It only tokenizes a payment method (credit card or bank account) but does not create a payment request. 
- You'll still have to submit a payment request to the payments (https://developer.justifi.ai/tag/Payments) or payment_intents api (https://developer.justifi.ai/tag/Payment-Intents) from the back end to process a payment.
- The response from the PaymentForm will provide a payment method id that can be passed to the payment request as payment method token.

Steps to setup/use the PaymentForm 
1. Grab the `account_id` of your sub account your want to create the payment method for
2. Pass the `account_id` to the PaymentForm as props
3. Grab the `client_id` from your Justifi dashboard under developers/api-keys and pass it in your frontend code - see example below
To process a payment
4. Pass the id from the PaymentForm response to the payments or payment intents api call from the backend

⚠️ Update the code example to show where and how the `client_id` needs to be passed 
If the `client_id` is supposed to be a prop in this component add it to the prop list and update the implementation steps!

**Comment by nhalm** [comment]
I'll update the code example and try to work in some verbiage on where to get the `client-id`
