### ISSUE TITLE
Investigate Dependabot alerts for Express.js malformed URLS

### ISSUE THREAD

**Issue by jakemer** [justifi-tech/web-component-library#438]
https://github.com/justifi-tech/web-component-library/security/dependabot/67
https://github.com/justifi-tech/payments-js/security/dependabot/83
https://github.com/justifi-tech/hosted-checkout-fe/security/dependabot/82

**Comment by colganmeanor** [comment]
Resolved this dependabot alert in all 3 of these repos.
