### ISSUE TITLE
BusinessFormStepped: country for representative missing

### ISSUE THREAD

**Issue by Claudia108** [justifi-tech/web-component-library#470]
**Is your feature request related to a problem? Please describe.**
Representative Step:
There is no `Country` field in the form and the form doesn't seem to autofill that information in the post request.
However, we require the representative country when the business gets provisioned.

<img width="1711" alt="Screen Shot 2024-04-23 at 2 05 03 PM" src="https://github.com/justifi-tech/web-component-library/assets/15485124/527eb263-ddd6-49a5-9e76-2b4e95daf531">

To fix: either provide country field in form or autofill.

**Comment by colganmeanor** [comment]
@Claudia108 - Hey, thanks for posting this! 

So, even though there is not a country field present in the DOM for the Representative or Owner fields - it is getting generated by the class instantiation on these steps and then getting sent to the backend with the POST request.

I see your screenshot here though, maybe its the preview body of a previous GET request...? I just double checked, and triple checked on the Production Storybook and it's working as I described. 

If you don't mind, would you please try again for me? And check the response / preview for either the POST request on the Representative Step, or the GET request you receive on the next step should also show that the Rep has the country filled in automatically on their address data. 

If you're seeing that I'm wrong about that, definitely let me know. 🙏🏻 

-------

That said, I'm totally supportive of adding the country fields to the form and showing them, even if they are disabled and auto-filling with `USA` similar to the Business Address.
