### ISSUE TITLE
CardForm `ready` event not being emitted after upgrading from 4.8.1 -> 4.8.2

### ISSUE THREAD

**Issue by jakemer** [justifi-tech/web-component-library#498]

**Comment by daltonconley** [comment]
I'm including the card form component inside a Lit component, so my use-case is probably different from the standard approaches. Also worth nothing, prior to this not working, I was listening for this event to bubble up from my shadow DOM and not attaching an event listener to the specific card form component. I noticed there were situations where the ready event would fire before my listener could get attached. This code snippet works in `4.8.1` but not `4.8.2`

```
import { defineCustomElement } from "@justifi/webcomponents/dist/module/justifi-card-form.js";
defineCustomElement();

@customElement('my-wrapper')
export class MyWrapper extends LitElement {
    async connectedCallback() {
      super.connectedCallback();

      this.shadowRoot?.addEventListener("ready", () => {
        this.loadingCardElement = false;
      });

      await this.doMyOtherStuff();
    }
}
```

**Comment by colganmeanor** [comment]
Hey @daltonconley - thanks for reporting this to us! 

I just pushed a new patch release that should resolve this issue. Please update to `4.12.2` to test this out - you should be able to catch those `ready` events now.
