### ISSUE TITLE
Checkout component: prop to choose selected payment method on load

### ISSUE THREAD

**Issue by Claudia108** [justifi-tech/web-component-library#631]
**Is your feature request related to a problem? Please describe.**
When no saved payment method is available the checkout component defaults to selecting the card form component. The size of the form pushes the BNPL payment option offscreen on mobile. The customer requests to auto select BNPL instead.

**Describe the solution you'd like**
Add a prop, e.g. `selected-payment-method`, that allows platforms to choose which payment method option is selected on load.
The prop could accept the following options: `cardForm`, `bankAccountForm`, `bnpl`, `paymentMethodGroup`. 
The naming and format of these options is totally up for debate, just putting ideas out there.
(I don't think `insurance` should be an option unless we expect a use case where a platform would only sell an insurance policy without a separate payment.)

We'll have to think through the use case of a payment_method_group. If there are any saved pms, do we still auto select the first in the payment method group or could the payment method id be passed in?

**Additional context**
![Screenshot 2024-08-05 at 1 25 06 PM](https://github.com/user-attachments/assets/96dd7992-8718-4497-b2fc-483b197d845c)

**Comment by jakemer** [comment]
@Claudia108 I think this was solved by instead making BNPL the default and first in the list when it's enabled?
