### ISSUE TITLE
Checkout: only show insurance option if account is enabled for insurance_payments

### ISSUE THREAD

**Issue by Claudia108** [justifi-tech/web-component-library#636]
**Describe the bug**
When checkout is loaded the insurance option is displayed in the checkout even if an account is not enabled for `insurance_payments`. 

**Expected behavior**
Check account settings when loading the component and only render insurance option if account has `insurance_payments` set to true even if insurance props are passed to the component.

**Comment by jakemer** [comment]
This is no longer needed, at least not at this time as insurance products are slotted into the checkout and therefore offer complete flexibility as to when to hide/show it
