### ISSUE TITLE
PayoutsList enhancements

### ISSUE THREAD

**Issue by jakemer** [justifi-tech/web-component-library#754]
- Remove "Type" column
- Remove "Paid Out To" column
- Replace "Account" column with "Sub Account Name"
- Update the "Paid out On" column to have just date, no time
- Remove "Actions" column header, and the column contains "CSV" link instead of download icon (icon may not match implementers icon set, and CSV is clearer anyways)
- Use the filters pane

**Comment by colganmeanor** [comment]
@jakemer should this be merged into `main` or `release-5.x.x` ?

Do we want to go ahead and add in the new column sorting prop in this PR?

**Comment by colganmeanor** [comment]
@jakemer 

Also - can you clarify the action for this bullet point? 

`Remove "Actions" column header, and the column contains "CSV" link instead of download icon (icon may not match implementers icon set, and CSV is clearer anyways)`
