### ISSUE TITLE
Payouts List: use deposits_at date 

### ISSUE THREAD

**Issue by Claudia108** [justifi-tech/web-component-library#755]
**Describe the bug**
The Payouts List component uses the `created_at` date (converted to local time) for the `Paid Out On` table column.

**Expected behavior**
The `Paid Out On` date should be the `deposits_at` date (converted to local time) as it is in the Payouts List in the customer dashboard.
The `Paid Out On` date should not display the time.

**Screenshots**
I can provide a screenshot for Adelie's implementation of the Payouts List component with payouts for the account `acc_1aPaRZJCgaZoXHtXcTmzIN`.

Here are the payouts on the customer dashboard for the same account and dates:
<img width="1709" alt="Screen Shot 2024-11-19 at 11 17 14 AM" src="https://github.com/user-attachments/assets/83be0fe6-8918-43ab-b7ae-cd19de5d3df2">

**Code Samples**
[Here](https://github.com/justifi-tech/web-component-library/blob/04bb33640bb6720efd79990635eeb415ff8bf49a/packages/webcomponents/src/components/payouts-list/payouts-list-core.tsx#L147-L148) is the code that pulls the `created_at` date and time.

**Comment by colganmeanor** [comment]
Discussed in slack this week - we will be using the `created_at` date for the web component. Closing this issue, will not complete this.
